### ISSUE TITLE
Car Design Dataset

### ISSUE THREAD

**Issue by niladridutta2001** [thuml/Transolver#5]
The link given for downloading car design dataset is not opening. Can it be checked?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest in our paper. 

The original link provided in this repository is from the official paper of https://dl.acm.org/doi/abs/10.1145/3197517.3201325

Since the car design dataset is not proposed by us, we do not have the copyright to secondary propagation of that data. Thus, I suggest you contact the authors of its official paper.
